### ISSUE TITLE
Matrix Functionality

### ISSUE THREAD

**Issue by briankalwat** [lindseydiloreto/craft-codeblock#2]
Have you verified that this works within a Matrix field? The following is rendering the static paragraph tag, but not the code that is actually stored in the codeblock field. Thoughts?

```
{% for block in entry.pageContent %}
   {% if block.type == 'customCode' %}
      {{ codeBlock|raw }}
      <p>stuff</p>
   {% endif %}
{% endfor %}
```

**Comment by lindseydiloreto** [comment]
Yes, in fact I _typically_ use it within a Matrix field.

The example you posted should definitely be showing the **rendered** version of `codeBlock`. I don't see any reason why it wouldn't... are you sure the `if` statement is being triggered?

**Comment by briankalwat** [comment]
I know it's being triggered because the paragraph tag below the variable is rendering when it hits the `customCode` block type.

**Comment by lindseydiloreto** [comment]
Can you give an example of a value in the Code Block field?

**Comment by lindseydiloreto** [comment]
If you remove the `raw` filter, are you seeing the unparsed version of your value?

**Comment by briankalwat** [comment]
![image](https://cloud.githubusercontent.com/assets/2465823/17632484/866893bc-6096-11e6-9b97-bb31d0db6db4.png)

Removing the Raw filter does not cause the value to be rendered either.

**Comment by lindseydiloreto** [comment]
Ahh, I see the error... You didn't specify the field as a subfield of `block`:

    {{ block.codeBlock|raw }}

I'd highly recommend turning on [devMode](https://craftcms.com/docs/config-settings#devMode)... It would have alerted you to that error.

**Comment by briankalwat** [comment]
@lindseydiloreto Thank you SO MUCH. Sorry to bother you with the newbie mistake. Thanks for taking the time to help me! 👍

**Comment by lindseydiloreto** [comment]
Np! Glad we got it sorted. :)
